ALTER TABLE `app` 
CHANGE COLUMN `logo` `logo` TINYTEXT NULL DEFAULT NULL ,
CHANGE COLUMN `alt_logo` `alt_logo` TINYTEXT NULL DEFAULT NULL ;

ALTER TABLE `usuarios` 
ADD COLUMN `logo` TINYTEXT NULL DEFAULT NULL AFTER `id_red_social`,
ADD COLUMN `alt_logo` TINYTEXT NULL DEFAULT NULL AFTER `logo`,
ADD COLUMN `tipo_logo` TINYINT(4) NULL DEFAULT NULL AFTER `alt_logo`;
