update encabezadoventas set pagada=true;
update encabezadoventas set pagada=false where id=17535;
update encabezadoventas set pagada=false where id=11345;
update encabezadoventas set pagada=false where id=12199;
update encabezadoventas set pagada=false where id=12753;
update encabezadoventas set pagada=false where id=12774;
update encabezadoventas set pagada=false where id=12971;
update encabezadoventas set pagada=false where id=12979;
update encabezadoventas set pagada=false where id=12980;
update encabezadoventas set pagada=false where id=13355;
update encabezadoventas set pagada=false where id= 14075;
update encabezadoventas set pagada=false where id=14116 ;
update encabezadoventas set pagada=false where id= 14776;
update encabezadoventas set pagada=false where id= 15278;
update encabezadoventas set pagada=false where id= 16362;
update encabezadoventas set pagada=false where id= 16785;
update encabezadoventas set pagada=false where id= 17277;
update encabezadoventas set pagada=false where id= 17320;
update encabezadoventas set pagada=false where id= 18371;
update encabezadoventas set pagada=false where id= 18382;
update encabezadoventas set pagada=false where id= 18671;